name = "Sustain-Vitae"
license = "MIT"
licenselink = "https://github.com/nurlansu/hugo-sustain/blob/master/LICENSE.md"
description = "Personal blog built with Bootstrap, powered by Hugo"
homepage = "https://github.com/nurlansu/hugo-sustain"
tags = ["blog", "minimal", "responsive"]
features = ["responsive", "syntax highlighting"]
min_version = 0.17

[author]
  name = "Nurlan Su"
  homepage = "https://github.com/nurlansu"

# If porting an existing theme
[original]
  name = "Sustain"
  homepage = "https://biomadeira.github.io/sustain/"
  repo = "https://github.com/biomadeira/sustain"
