baseurl = "https://example.com/"
languageCode = "en-US"
title = "Chris Turner"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain-vitae"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Chris Turner"
  description = "Describe your website"
  css_prefix = "sustain"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

[params.vitae]
  website = "git.io/sustain"
  website_full = "https://demo.nurlan.co/hugo-sustain/"
  tel = "+44 0000 000000"
  tel_full = "+440000000000"
  google_maps = "https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL"
  address = "44 Perth Street"
  postcode = "EH3 5BL"
  city = "Edinburgh"
  country = "United Kingdom"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/vitae/"
